---
name: Publish

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  actions: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: false
        sparse-checkout: |
          Containerfile
        sparse-checkout-cone-mode: false

    - name: Determine tags
      id: tags
      run: |
        # Extracts the base container image tag out of the containerfile
        export TAGS=$(cat Containerfile | grep FROM | cut -d ':' -f 2 | cut -d '@' -f 1)

        echo "tags=$TAGS" >>$GITHUB_OUTPUT
    outputs:
      tags: ${{ steps.tags.outputs.tags }}

  build:
    name: Build
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    needs:
    - prepare
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      tags: ${{ needs.prepare.outputs.tags }}
      registry: ghcr.io/freedomofpress/gke-gs-bucket-backup

